### PR TITLE
fix: Update subscription validation to work with SSO

### LINKED ISSUE #1: Support SSO auth
I have an O'Reilly account via acm.org which seems to use a different auth mechanism (SSO). Please consider adding support for SSO.

### PR DESCRIPTION
**Pull request by FreeMasen**
This PR adds support for validating the subscription by using `/api/v1/` instead of `/api/v1/payments/next_billing_date/`, since SSO users don't always have access to managing the payment for their account. `/api/v1/`  seems to provide an overview of the currently logged in user which has both a `subscription` field and a `trail` field detailing when those payments will expire.

I have validated this works with both an SSO account and a trail membership. I believe this should close #1

### CODE REVIEW

File: src/client.rs [hunk 1]
```diff
@@ -82,26 +82,29 @@ impl OreillyClient<Unauthenticated> {
...
-            .context("Failed to parse next billing date")?;
-
-        let local: DateTime<Local> = DateTime::from(expiration);
-
-        info!("Subscription expiration: {}", local);
-
-        if expiration < Utc::now() {
-            error!("Subscription expired on {}", local);
+        let expiration = if let Some(sub_exp) = billing.subscription.cancellation_date {
+            let dt = NaiveDate::parse_from_str(&sub_exp, "%Y-%m-%d")
```
Comment (FreeMasen) [inline src/client.rs:93]: for some reason, my SSE account's subscription `cancellation_date` is in this format. It might be good to test this parsing still works with a paid/non-trial/non-sso account (of which I do not have).

**Comment by FreeMasen** [comment]
I did validate that 2 downloads of the same ebook seem to be identical, once using the SSO+Cooke and the other using a trial account+username/password.

**Comment by hurlenko** [comment]
Hi! Thanks for the update 🙂 
I don't have a paid account either so let's merge it for now and see if anyone fires a bug report 😆 
The trial one works fine for me, too. Thanks again!
